### ISSUE TITLE
Problem with Model Browser :(

### ISSUE THREAD

**Issue by MTF5** [sunnyark/civitai-shortcut#105]
HI sunnyark,

There are several errors when selecting a shortcut in the Model Browser. The Register Model works OK but not the Model Browser.
I am using: lllyasviel / stable-diffusion-webui-forge  BUT  if I switch to  AUTOMATIC1111 / stable-diffusion-webui  everything works fine.
Also some civitai url shows the message  "Connection errored out.", it only happens with lllyasviel  version.

The error is:
Traceback (most recent call last):
  File "D:\AI\GUI\Stable Diffusion WebUI Forge\webui_forge_cu121_torch231\system\python\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\AI\GUI\Stable Diffusion WebUI Forge\webui_forge_cu121_torch231\system\python\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\AI\GUI\Stable Diffusion WebUI Forge\webui_forge_cu121_torch231\system\python\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "D:\AI\GUI\Stable Diffusion WebUI Forge\webui_forge_cu121_torch231\system\python\lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "D:\AI\GUI\Stable Diffusion WebUI Forge\webui_forge_cu121_torch231\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\AI\GUI\Stable Diffusion WebUI Forge\webui_forge_cu121_torch231\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\AI\GUI\Stable Diffusion WebUI Forge\webui_forge_cu121_torch231\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\AI\GUI\Stable Diffusion WebUI Forge\webui_forge_cu121_torch231\system\python\lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "D:\AI\GUI\Stable Diffusion WebUI Forge\webui_forge_cu121_torch231\webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\civitai_shortcut_action.py", line 228, in on_sc_gallery_select
    sc_model_id = setting.get_modelid_from_shortcutname(shortcut) #shortcut[0:shortcut.find(':')]
  File "D:\AI\GUI\Stable Diffusion WebUI Forge\webui_forge_cu121_torch231\webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\setting.py", line 414, in get_modelid_from_shortcutname
    return sc_name[sc_name.rfind(':') + 1:]
AttributeError: 'dict' object has no attribute 'rfind'

**Comment by firrae** [comment]
Getting the same issue with the stock Forge UI
