### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by agarzon** [sunnyark/civitai-shortcut#15]
```
Error loading script: civitai_shortcut.py
Traceback (most recent call last):
  File "C:\Users\User\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\User\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\User\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_shortcut.py", line 86, in <module>
    init_civitai_shortcut()
  File "C:\Users\User\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_shortcut.py", line 83, in init_civitai_shortcut
    model.update_downloaded_model()
  File "C:\Users\User\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\model.py", line 26, in update_downloaded_model
    Downloaded_Models, Downloaded_InfoPath = get_model_path()
ValueError: too many values to unpack (expected 2)
```

**Comment by sunnyark** [comment]
I'm sorry. I have made the correction.
