### ISSUE TITLE
Error when I click on "Scan downloaded models for shortcut registration"

### ISSUE THREAD

**Issue by Swoogx** [sunnyark/civitai-shortcut#16]
I have an error that stops the scan process:

Traceback (most recent call last):
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\stable-diffusion-webui-master\extensions\civitai-shortcut\scripts\civitai_manager_libs\setting_action.py", line 173, in on_scan_to_shortcut_click
    ishortcut_action.scan_downloadedmodel_to_shortcut(progress)
  File "F:\stable-diffusion-webui-master\extensions\civitai-shortcut\scripts\civitai_manager_libs\ishortcut_action.py", line 562, in scan_downloadedmodel_to_shortcut
    add_ISC = ishortcut.add(add_ISC, str(modelid),False,progress)
  File "F:\stable-diffusion-webui-master\extensions\civitai-shortcut\scripts\civitai_manager_libs\ishortcut.py", line 393, in add
    model_info = write_model_information(model_id, register_information_only, progress)
  File "F:\stable-diffusion-webui-master\extensions\civitai-shortcut\scripts\civitai_manager_libs\ishortcut.py", line 104, in write_model_information
    model_info = civitai.get_model_info(modelid)
  File "F:\stable-diffusion-webui-master\extensions\civitai-shortcut\scripts\civitai_manager_libs\civitai.py", line 57, in get_model_info
AttributeError: 'str' object has no attribute 'keys'

**Comment by sunnyark** [comment]
@Swoogx 
I have noticed an error when loading a deleted model on the Civitai site. It seems that Civitai's handling of missing models has been changed.  I have made the necessary updates to the question. Could you please confirm if the issue still persists even after updating the extension through "check for updates" option?

**Comment by Swoogx** [comment]
I still have this problem, even though everything is up to date :(

**Comment by sunnyark** [comment]
@Swoogx If the same error occurs, it seems that the update was not applied properly. Did the same error occur? Please try turning off sdui and restarting it after updating the extension.

**Comment by Swoogx** [comment]
I had to uninstall the extension completely (deactivate, delete files, ...) and reinstall it. Now everything works fine!
Sorry for the inconvenience.
