### ISSUE TITLE
"Civitai Model Information" tab not working

### ISSUE THREAD

**Issue by fsilveiradev** [sunnyark/civitai-shortcut#19]
Yesterday it was working fine, but today it seems the extension fails to retrieve the model information from Civitai.

`Startup time: 138.8s (import torch: 42.2s, import gradio: 2.1s, import ldm: 4.9s, other imports: 9.6s, list SD models: 0.3s, setup codeformer: 0.5s, load scripts: 20.6s, load SD checkpoint: 41.7s, create ui: 12.2s, gradio launch: 4.4s).
Traceback (most recent call last):
  File "G:\AI\SDWebui\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\AI\SDWebui\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "G:\AI\SDWebui\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\AI\SDWebui\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\AI\SDWebui\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "G:\AI\SDWebui\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "G:\AI\SDWebui\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\civitai_action.py", line 434, in on_load_model
    return load_model(modelid, ver_index)
  File "G:\AI\SDWebui\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\civitai_action.py", line 441, in load_model
    model_info,versionid,version_name,model_url,downloaded_versions_list,model_type,versions_list,dhtml,triger,files,title_name,images_url,images_meta,vs_foldername = get_model_information(modelid,None,ver_index)
  File "G:\AI\SDWebui\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\civitai_action.py", line 522, in get_model_information
    dhtml, triger, files = get_version_description(version_info,model_info)
  File "G:\AI\SDWebui\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\civitai_action.py", line 617, in get_version_description
    model_tags = [tag["name"] for tag in model_info["tags"]]
  File "G:\AI\SDWebui\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\civitai_action.py", line 617, in <listcomp>
    model_tags = [tag["name"] for tag in model_info["tags"]]
TypeError: string indices must be integers`

The Civitai User Gallery and other tabs seems to be working fine, it is just the Civitai Model Information.
After getting this error I made sure to update the extension and restart the Webui, but didn't resolve. I'm guessing it is something on the website's side that changed?

**Comment by sunnyark** [comment]
This is an issue caused by changes in the model information specification in Civitai. Data update is required. I have uploaded the fix urgently. To update the data, please perform "Manage -> Scan and Update Model -> Update the model information for the shortcut," and it will "download and retrieve the latest information.
You need to update Civitai Shortcut first.

**Comment by fsilveiradev** [comment]
That was quick! Thanks!
Loved the latest changes btw
