### ISSUE TITLE
Civitai Shortcut tab is not showing

### ISSUE THREAD

**Issue by uaewebmaster** [sunnyark/civitai-shortcut#20]
I am getting the following error in the terminal : 

Error executing callback ui_tabs_callback for D:\Stable Diffusion\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_shortcut.py
Traceback (most recent call last):
  File "D:\Stable Diffusion\stable-diffusion-webui\modules\script_callbacks.py", line 134, in ui_tabs_callback
    res += c.callback() or []
  File "D:\Stable Diffusion\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_shortcut.py", line 131, in on_ui_tabs
    civitai_shortcut_ui()
  File "D:\Stable Diffusion\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_shortcut.py", line 67, in civitai_shortcut_ui
    refresh_recipe = recipe_action.on_ui(recipe_input, civitai_tabs, civitai_assistance_tabs)
  File "D:\Stable Diffusion\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\recipe_action.py", line 89, in on_ui
    recipe_classification_list = gr.Dropdown(label="Prompt Recipe Classification", choices=[setting.PLACEHOLDER] + recipe.get_classifications(), value=setting.PLACEHOLDER, interactive=True, multiselect=False)
TypeError: can only concatenate list (not "NoneType") to list

This happened after updating the Civitai Shortcut 10 minutes ago.

Your help is extremely appreciated.

**Comment by sunnyark** [comment]
@uaewebmaster I'm sorry. I have made the correction.
