### ISSUE TITLE
Error if there is no civitai information

### ISSUE THREAD

**Issue by taro6222** [sunnyark/civitai-shortcut#4]
Traceback (most recent call last):
  File "f:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "f:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "f:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "f:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "f:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "f:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\civitai_shortcut_action.py", line 86, in on_scan_to_shortcut_click
    ishortcut_action.scan_downloadedmodel_to_shortcut(progress)
  File "F:\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\ishortcut_action.py", line 216, in scan_downloadedmodel_to_shortcut
    add_ISC = ishortcut.add(add_ISC, str(modelid))
  File "F:\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\ishortcut.py", line 330, in add
    util.printD("IMG..: " + str(def_image))
UnboundLocalError: local variable 'def_image' referenced before assignment

It is believed that the error occurs when there is no civitai information.

콘솔에 오류가 발생한 아이템(로라인지 체크포인트인지 등)의 정보가 없어 대처할 수 방법이 없어 답답한 부분이 있습니다.

좋은 확장프로그램 배포해 주셔서 무척 고맙습니다.

**Comment by sunnyark** [comment]
감사합니다. 수정하였습니다.
