### ISSUE TITLE
seem not support older versions

### ISSUE THREAD

**Issue by ioritree** [sunnyark/civitai-shortcut#6]
This plugin does not seem to support older versions
stable diffusion 22bcc7be version can see plugin button on page ,but older versions no appear anything on page.

**Comment by sunnyark** [comment]
This plugin requires gradio: 3.23.0.

**Comment by ioritree** [comment]
> This plugin requires gradio: 3.23.0.
update to 3.23.0 still no see.

**Comment by sunnyark** [comment]
![스크린샷 2023-04-20 150341](https://user-images.githubusercontent.com/40237431/233273036-c09b2116-3ed8-4602-9319-64bc0c66e0d8.png)
This is the environment that I am using. 
I have tried uninstalling and reinstalling the program, but I still don't know what the problem is. 
Also, what operating system are you using? I haven't been able to test it on other systems as I'm running on Windows.

**Comment by sunnyark** [comment]
I attempted to install the software on Ubuntu running under WSL2,  I don't have a testing machine, but I couldn't find any other issues. Why isn't it working?

**Comment by hobolyra** [comment]
Same issue here, can't see the tab or options for this, even though I don't get any load issues when starting Automatic1111

**Comment by sunnyark** [comment]
@hobolyra When loading, the extension may not have loaded properly. Does the loading message display the version information of this extension? Like this: 'Civitai Shortcut: V1.5.4'.

**Comment by GianPieroA** [comment]
It seems a compatibility issue with Gradio 3.32.0 to me


Civitai Shortcut: V1.5.1
Civitai Shortcut: shortcut update start
Error executing callback ui_tabs_callback for D:\StableDiffusionUI\extensions\civitai-shortcut\scripts\civitai_shortcut.py
Traceback (most recent call last):
  File "D:\StableDiffusionUI\modules\script_callbacks.py", line 151, in ui_tabs_callback
    res += c.callback() or []
  File "D:\StableDiffusionUI\extensions\civitai-shortcut\scripts\civitai_shortcut.py", line 112, in on_ui_tabs
    civitai_shortcut_ui()
  File "D:\StableDiffusionUI\extensions\civitai-shortcut\scripts\civitai_shortcut.py", line 73, in civitai_shortcut_ui
    civitai_tabs.select(
  File "D:\StableDiffusionUI\venv\lib\site-packages\gradio\events.py", line 132, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
  File "D:\StableDiffusionUI\venv\lib\site-packages\gradio\blocks.py", line 268, in set_event_trigger
    "outputs": [block._id for block in outputs],
  File "D:\StableDiffusionUI\venv\lib\site-packages\gradio\blocks.py", line 268, in <listcomp>
    "outputs": [block._id for block in outputs],
AttributeError: 'tuple' object has no attribute '_id'
