### ISSUE TITLE
Unable to use error after update

### ISSUE THREAD

**Issue by suaixx** [sunnyark/civitai-shortcut#60]
After the update, the format of the CivitaiShortCut.json file has added a time and date. I have checked that the previous version does not have it. I don’t know if it is because of this problem that it cannot be read.

**Comment by suaixx** [comment]
*** Error executing callback ui_tabs_callback for E:\NovelAI\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_shortcut.py
    Traceback (most recent call last):
      File "E:\NovelAI\stable-diffusion-webui\modules\script_callbacks.py", line 153, in ui_tabs_callback
        res += c.callback() or []
      File "E:\NovelAI\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_shortcut.py", line 114, in on_ui_tabs
        civitai_shortcut_ui()
      File "E:\NovelAI\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_shortcut.py", line 50, in civitai_shortcut_ui
        refresh_civitai_sc_browser, refresh_civitai_information = civitai_shortcut_action.on_ui(recipe_input, shortcut_input, civitai_tabs)
      File "E:\NovelAI\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\civitai_shortcut_action.py", line 42, in on_ui
        sc_gallery, refresh_sc_browser, refresh_sc_gallery = sc_browser_page.on_ui()
      File "E:\NovelAI\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\sc_browser_page.py", line 137, in on_ui
        thumb_list , thumb_totals, thumb_max_page  = get_thumbnail_list(None,False,None,None,None,1,shortcut_column,shortcut_rows_per_page)
      File "E:\NovelAI\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\sc_browser_page.py", line 92, in get_thumbnail_list
        if bool(v['nsfw']) and setting.NSFW_filtering_enable:
    KeyError: 'nsfw'

**Comment by sunnyark** [comment]
Is the error message you provided the same as the one that first occurred? If they are the same, it doesn't seem to be due to the additional date. Though the exact reason is not clear, it appears that the 'nsfw' key has been removed from the shortcut data, causing a key error. I will add a validation routine for the key value and try to update it.

**Comment by suaixx** [comment]
Thank you, just updated and it can be used normally

**Comment by sunnyark** [comment]
If you encounter any more issues or have any feedback, please let us know. It would be greatly appreciated. Thank you.

**Comment by 95121808** [comment]
修改setting.py,路径就是上面老哥YOURPATH/stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\内，167行True改false.如果这不是一个好建议，请告诉我，我会删除这条信息
