### ISSUE TITLE
Civitai Shortcut tab is not showing update

### ISSUE THREAD

**Issue by aijpcs** [sunnyark/civitai-shortcut#73]
It was available in the old version before, but after the update later, the tab is gone
Here is the error message:
Civitai Shortcut: v1.6.4
Civitai Shortcut: shortcut update start
*** Error executing callback ui_tabs_callback for H:\AI\sd-webui\extensions\civitai-shortcut\scripts\civitai_shortcut.py
    Traceback (most recent call last):
      File "H:\AI\sd-webui\modules\script_callbacks.py", line 153, in ui_tabs_callback
        res += c.callback() or []
      File "H:\AI\sd-webui\extensions\civitai-shortcut\scripts\civitai_shortcut.py", line 114, in on_ui_tabs
        civitai_shortcut_ui()
      File "H:\AI\sd-webui\extensions\civitai-shortcut\scripts\civitai_shortcut.py", line 50, in civitai_shortcut_ui
        refresh_civitai_sc_browser, refresh_civitai_information = civitai_shortcut_action.on_ui(recipe_input, shortcut_input, civitai_tabs)
      File "H:\AI\sd-webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\civitai_shortcut_action.py", line 44, in on_ui
        sc_gallery, refresh_sc_browser, refresh_sc_gallery = sc_browser_page.on_ui()
      File "H:\AI\sd-webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\sc_browser_page.py", line 207, in on_ui
        reset_filter_btn.click(
    UnboundLocalError: local variable 'reset_filter_btn' referenced before assignment

**Comment by sunnyark** [comment]
I'm sorry. I've made the changes. If you update, they will be reflected.

**Comment by aijpcs** [comment]
OK, it's out, thank you
