### ISSUE TITLE
error on loading user gallery

### ISSUE THREAD

**Issue by DavidAntonin** [sunnyark/civitai-shortcut#90]
When I try to open user gallery i get error:
Civitai Shortcut: Request failed with status code: 500
Civitai Shortcut: Request failed with status code: 500
Traceback (most recent call last):
  File "D:\sd.webui\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\sd.webui\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\sd.webui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\sd.webui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\sd.webui\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\sd.webui\webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\civitai_gallery_action.py", line 443, in on_usergal_page_url_change
    return load_gallery_page(usergal_page_url, paging_information)
  File "D:\sd.webui\webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\civitai_gallery_action.py", line 508, in load_gallery_page
    image_url, images_meta = get_gallery_information(usergal_page_url, False)
  File "D:\sd.webui\webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\civitai_gallery_action.py", line 531, in get_gallery_information
    images_url, images_meta , images_list = get_user_gallery(modelid, page_url, show_nsfw)
  File "D:\sd.webui\webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\civitai_gallery_action.py", line 548, in get_user_gallery
    if "meta" in image_info:
TypeError: argument of type 'NoneType' is not iterable

**Comment by ruslanyar** [comment]
got the same error
