### ISSUE TITLE
can not Register Model

### ISSUE THREAD

**Issue by suaixx** [sunnyark/civitai-shortcut#95]
Traceback (most recent call last):
  File "c:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "c:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "c:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "c:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "c:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "c:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "c:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\civitai_shortcut_action.py", line 250, in on_civitai_internet_url_upload
    modelids = ishortcut_action.upload_shortcut_by_files(files, register_information_only, progress)
  File "C:\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\ishortcut_action.py", line 898, in upload_shortcut_by_files
    add_ISC = ishortcut.add(add_ISC, model_id, register_information_only, progress)
  File "C:\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\ishortcut.py", line 848, in add
    if setting.NSFW_levels.index(img_dict["nsfw"]) < cur_nsfw_level:
KeyError: 'nsfw'

**Comment by RedAISkye** [comment]
Same issue here.

I tried toggling the NSFW filter and changing the API key as well.
