### ISSUE TITLE
ModuleNotFoundError after update

### ISSUE THREAD

**Issue by NicolasGJ16** [sunnyark/civitai-shortcut#98]
After updating the extension in Auto1111 and reloading the UI or just restarting it whole, I get: 
ModuleNotFoundError: No module named 'modules.infotext_utils'

Here is the whole cmd log:
` *** Error loading script: civitai_shortcut.py
    Traceback (most recent call last):
      File "E:\AI\stable-diffusion-webui-mine\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\AI\stable-diffusion-webui-mine\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\AI\stable-diffusion-webui-mine\extensions\civitai-shortcut\scripts\civitai_shortcut.py", line 11, in <module>
        from scripts.civitai_manager_libs import civitai_shortcut_action
      File "E:\AI\stable-diffusion-webui-mine\extensions\civitai-shortcut\scripts\civitai_manager_libs\civitai_shortcut_action.py", line 13, in <module>
        from . import ishortcut_action
      File "E:\AI\stable-diffusion-webui-mine\extensions\civitai-shortcut\scripts\civitai_manager_libs\ishortcut_action.py", line 7, in <module>
        import modules.infotext_utils as parameters_copypaste
    ModuleNotFoundError: No module named 'modules.infotext_utils'

--- `

**Comment by sunnyark** [comment]
The code has been modified due to a change in the module name in the latest version of Auto1111. Updating Auto1111 will resolve the issue.

**Comment by NicolasGJ16** [comment]
Oh okok, thanks!

**Comment by NicolasGJ16** [comment]
Oh okok, thanks!
